name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: [aarch64, armv7]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t ghcr.io/iced-rs/${{ matrix.image }}:latest -f Dockerfile.${{ matrix.image }} .
    - name: Log in to the GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish image
      run: docker push ghcr.io/iced-rs/${{ matrix.image }}:latest
